use_default_settings: true

general:
  instance_name: "Earthly Search"
  enable_metrics: false

search:
  safe_search: 1
  default_lang: "en"
  formats:
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"

outgoing:
  request_timeout: 4.0
  max_request_timeout: 8.0
  pool_connections: 40
  pool_maxsize: 10
